### ISSUE TITLE
Amazon Alexa is shown twice

### ISSUE THREAD

**Issue by gsmet** [quarkusio/extensions#101] opened 2023-02-06 12:35 UTC
We have:
- one entry for the Quarkiverse extension
- one entry for an old version of the extension that lived in the main repo

We should only keep the Quarkiverse extension.

![extensions-amazon-alexa](https://user-images.githubusercontent.com/1279749/216972793-b6748433-e4fc-4bd8-b17a-7c78add963b8.png)

**Comment by holly-cummins** [comment] 2023-02-06 12:53
I think this is a duplicate of #73 , do you agree? The issue is that the extension has been published twice, with two different group ids. When we switched to including the group id in the id, we ended up showing both of them.

**Comment by gsmet** [comment] 2023-02-06 12:59
Well, I wouldn't say it's a duplicate because that's not a behavior we want for these particular extensions. The extensions from `io.quarkus` have been discontinued for a long time and we shouldn't show them.

Not that it's not exactly a general rule because there are exceptions such as `quarkus-logging-json`.

**Comment by holly-cummins** [comment] 2023-02-06 13:05
That's exactly the behaviour that we'll get with #73. We won't show the older extensions on the front page, only the newer ones. On the page for the newer extension, and then at the bottom it will say 'there's a much older version of this extension in a different group id, do you want to see that?', with the link. 

For the more general case of not showing very old extensions which *haven't* been superseded by a more recent extension with a different group id, perhaps we want an extra age-related filter? However, by design, we don't filter on the platform as code.quarkus.io does. It's a deliberate design decision to show all extensions, to allow people to start with the extension they want and work to the platform they need, instead of the opposite.

**Comment by gsmet** [comment] 2023-02-06 13:08
But #73 is closed and I still see the issue? So I don't understand what you're saying :).

**Comment by holly-cummins** [comment] 2023-02-06 13:21
Argh, sorry, wrong link! #73 *created* the problem, #76 is tracking the fix. So I think this is a duplicate of #76. I get a bit muddled between de-duplicate and re-duplicate and which one is de-duplicating and which one is re-duplicating :).

**Comment by gsmet** [comment] 2023-02-06 13:39
I think it's a bit unfortunate this issue happens for the very first extensions as it's pretty confusing.
TBH, for now, I would just hardcode some rules to get this worked around properly. It's not as if this happened often.

But I'll let you be the judge of that :).

Closing as it's indeed a duplicate of #76.

**Comment by holly-cummins** [comment] 2023-02-06 16:55
I see your point about it being on the first extensions in the list (at least until I implement ordering by release date or popularity). I agree that does make it more urgent.

**Closed by holly-cummins** 2023-02-06 16:55 UTC
